name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    dev:
        name: dev
        runs-on: ubuntu-latest
        steps:
         - run: echo "running dev stage"
    contoso:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: dev/contoso
        secrets: inherit
        needs: [dev]
    qa:
        name: qa
        needs: [dev,contoso]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running qa stage"
    qasite:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: qa/qasite
        secrets: inherit
        needs: [qa]
    scaledsite:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: qa/scaledsite
        secrets: inherit
        needs: [qa]
    prod:
        name: prod
        needs: [qa,qasite,scaledsite]
        runs-on: ubuntu-latest
        steps:
         - run: echo "running prod stage"
    prodsite:
        uses: ./.github/workflows/site-cd-workflow.yml
        with:
            working-directory: prod/prodsite
        secrets: inherit
        needs: [prod]
